language: ruby
before_install:
  - sudo apt-get install libxml2-dev libxslt1-dev nmap
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
script: rake test
